;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                                  Init.INC                                  ;
;                    Initialization Constants for mp3 player                 ;
;                                 Include File                               ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; This file contains the definitions for the chip selects for the mp3 player
; 
;
; Revision History:
; 	
; 04/24/02	Chirath Thouppuarachchi		Creation
;


; Register locations and names

LMCS_REG	EQU	0FFA2H
UMCS_REG	EQU	0FFA0H
MMCS_REG	EQU	0FFA6H
PACS_REG	EQU	0FFA4H
MPCS_REG	EQU	0FFA8H