;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                                  SDL.INC                                   ;
;                                                                            ;
;                                 Include File                               ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; This file contains the definitions for the Serial Download Path Functions
;
;
; Revision History:
;    18/03/2002    Chirath Neranjena  initial revision 

;max path size
Path_Size	EQU	256

; magnet definitions
MagnetOn	EQU	1
MagnetOff	EQU	0

Magnet_Neutral	EQU	0


; Angle and Vert Defnitions
Absolute	EQU	0
Relative	EQU	1
